### ISSUE TITLE
cannot read write data with device HID Global OMNIKEY 5422

### ISSUE THREAD

**Issue by fudnaja** [hidglobal/HID-OMNIKEY-Sample-Codes#1]
Select Menu 1 -> 2 Reader Name: HID Global OMNIKEY 5422 -> 2 User EEPROM
-> Read Example

Connecting to HID Global OMNIKEY 5422 Smardcard Reader 0...
Connected
Connection ModeL Direct
An error has occured: Incorrect function
Reader connection closed

Please help me.

**Comment by fudnaja** [comment]
I change to device HID Global OMNIKEY 5422CL

**Comment by ghost** [comment]
Hello fudnaja,
When winscard raise "Incorrect Function" error it typically means that that you try to call function that is incorrect in given context. I assume that you did not insert the smart card in reader slot when the example was invoked. You got few choices here, either insert card to the reader slot (contact card for a HID Global OMNIKEY 5422, contactless card for the one with CL suffix) or if you want to work without smart card then enable CCID ESCAPE commands in device driver configuration.
If you work on windows platform then you can install HID OMNIKEY CCID DRIVER which supports CCID ESCAPE commands by default.
