### ISSUE TITLE
Read Data OMNIKEY 5422

### ISSUE THREAD

**Issue by fudnaja** [hidglobal/HID-OMNIKEY-Sample-Codes#2]
Hello,

I have a new problem,
I'm write data to card no.1 and read data is ok,
after that, i'm read data from card no.2, why data from card no.1 is writed to card no.2 ???

Help me check from your application test
Thank you.

1. Smart Card Readers -> 3. PCSC Reader Name: HID Gloebal ONIKEY 5422CL Smartcard Reader 0 -> 2. User EEPROM -> 2. Write Example

**Comment by ghost** [comment]
Hello,

User EEPROM is a memory space in reader itself not in a smart card, as such you have written data to the reader EEPROM memory which is shared between both contactless and contact slot.

I hope this clear out your problem.
