### ISSUE TITLE
how to implement for 5427ck

### ISSUE THREAD

**Issue by alexanderghose** [hidglobal/HID-OMNIKEY-Sample-Codes#3]
hi team, i notice that this code doesn't support the omnikey 5427ck. would you have any suggestions on how to get this running for the 5427CK?  Or any other resources that may help.

**Comment by ghost** [comment]
Hello @alexanderghose 
Any resources or support regarding 5427CK are available via [Development Center].(https://www.hidglobal.com/developer-center/omnikey-5x27ck-developer-center)

**Comment by jaysel** [comment]
Or raise a ticket via support@omnikey.com. However, only limited development support is offered.

**Comment by g-fvergara** [comment]
I recently wanted to implement one of these readers (5427CK) but found no info online. How do we get a hold on a dev license for the dev center? I recently bought this product and needed to do an integration for a client

**Comment by jaysel** [comment]
Purchase of an OMNIKEY 5427 does not give access to the Developer Centre https://www.hidglobal.com/developer-center/omnikey-5x27ck-developer-center
You need to order the OMNIKEY 5x27CK Developers Toolkit. A license code for the OMNIKEY 5427 Developer Center is contained in the OMNIKEY 5x27CK Developers Toolkit (DTK). 
With this license code, the customer can create up to three download accounts for the Developers Center, where he will get updated documentation and tools during the lifetime of the product. 
The Developers Toolkit contains sample readers, sample cards, all documentation, sample software and several tools for developing with the OMNIKEY 5427CK and related readers. 

With the reader only, the customer has no access rights to the Developer Center and any programming samples or special tools. 

For more information about ordering Hid Global products please contact your distributor or refer to the following page: https://www.hidglobal.com/documents/how-to-order

**Comment by ghost** [comment]
Resolved
