### ISSUE TITLE
5427G2 Support

### ISSUE THREAD

**Issue by jbritz** [hidglobal/HID-OMNIKEY-Sample-Codes#4]
Hi all,

Thank you for all the examples.
Any chance that you can include support for the 5427G2 omnikey reader in this example?

Regards,
Jacques

**Comment by jaysel** [comment]
The 5427G2 is configurable via Keyboard Wedge. What is your use case for sample codes?

**Comment by jbritz** [comment]
Hi @jaysel,
I need to use the 5427G2 in CCID mode with  PC/SC.

**Comment by jaysel** [comment]
I don't think I have anything - but let me check

**Comment by jbritz** [comment]
Hi @jaysel,
Just checking in, have you had a chance yet to look at this?

**Comment by jaysel** [comment]
Yes...sorry, you can only get these if you have a developer account at HID. They do not give this out as part of the free user support

**Comment by jbritz** [comment]
Thank you
