### ISSUE TITLE
HID Omnikey 5427 "The drivers for this device are not installed. (Code 28)"

### ISSUE THREAD

**Issue by Ni2Be** [hidglobal/HID-OMNIKEY-Sample-Codes#8]
We are integrating the Omnikey 5427 and connected to a win 10 notebook it says:
```
The drivers for this device are not installed. (Code 28)
There are no compatible drivers for this device.
To find a driver for this device, click Update Driver.
```
It is working despite the error, but is that normal behaviour?

![image](https://user-images.githubusercontent.com/16502655/181769199-60ac3b5c-c0b5-432e-8a8f-86a31fb11ba7.png)

**Comment by stilldisturbing** [comment]
There is a driver that can be loaded which enabled you to configure it via the EEEthernet Emulation Mode (web page on the device).  The driver (think it is the latest) is at [https://www.hidglobal.com/drivers/34881](https://www.hidglobal.com/drivers/34881) Once installed the reader can be accessed via a web browser at 192.168.63.99.  The documentation for all the modes/config is at [OMNIKEY 5X27CK KEYBOARD WEDGE 
CONFIGURATION](https://www.hidglobal.com/sites/default/files/resource_files/5127-902_e.1_-_omnikey_5x27ck_keyboard_wedge_user_guide.pdf)

Hope this helps.

**Comment by mjedrzejas** [comment]
EEM driver is required to configure OMNIKEY 5427 over a web interface as mentioned by @stilldisturbing . Without it, the device will work correctly. Once installed you will be able to see the following device under network adapters:
![image](https://user-images.githubusercontent.com/1933396/181784386-5a5a1fa0-8543-44d0-96f6-31a935416a78.png)

The reader itself should appear under Smart card readers and it can work with the generic CCID driver from Windows.

**Comment by Ni2Be** [comment]
Perfect, thanks for the quick response 👍
